-- ============================================
-- HabitRefactor - AI Analyses Schema Upgrade
-- Makes legacy `migration.sql` ai_analyses compatible
-- with daily/weekly insights generated by the backend.
-- Safe to run multiple times.
-- ============================================

ALTER TABLE IF EXISTS public.ai_analyses
  ADD COLUMN IF NOT EXISTS analysis_type analysis_type,
  ADD COLUMN IF NOT EXISTS insights JSONB,
  ADD COLUMN IF NOT EXISTS recommendations JSONB,
  ADD COLUMN IF NOT EXISTS trigger_patterns JSONB,
  ADD COLUMN IF NOT EXISTS tomorrow_action TEXT,
  ADD COLUMN IF NOT EXISTS motivational_close TEXT,
  ADD COLUMN IF NOT EXISTS confidence_score NUMERIC,
  ADD COLUMN IF NOT EXISTS is_read BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS is_bookmarked BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS user_feedback TEXT;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'ai_analyses'
      AND column_name = 'type'
  ) THEN
    UPDATE public.ai_analyses
    SET analysis_type = COALESCE(analysis_type, "type")
    WHERE analysis_type IS NULL;
  END IF;
END $$;

UPDATE public.ai_analyses
SET analysis_type = 'daily_review'
WHERE analysis_type IS NULL;

ALTER TABLE IF EXISTS public.ai_analyses
  ALTER COLUMN analysis_type SET NOT NULL;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'ai_analyses'
      AND column_name = 'full_analysis'
      AND data_type = 'jsonb'
  ) THEN
    ALTER TABLE public.ai_analyses
      ALTER COLUMN full_analysis DROP DEFAULT;

    ALTER TABLE public.ai_analyses
      ALTER COLUMN full_analysis TYPE TEXT
      USING CASE
        WHEN full_analysis IS NULL THEN ''
        WHEN jsonb_typeof(full_analysis) = 'string' THEN full_analysis #>> '{}'
        ELSE full_analysis::text
      END;

    ALTER TABLE public.ai_analyses
      ALTER COLUMN full_analysis SET DEFAULT '';
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_analyses_user
  ON public.ai_analyses(user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_analyses_type
  ON public.ai_analyses(user_id, analysis_type);

-- Done.
