-- ============================================
-- Knowledge Base Seed Data
-- Wisdom for RAG pipeline (run after migration.sql)
-- ============================================

-- David Goggins
INSERT INTO knowledge_base (source, category, title, content, metadata) VALUES
('David Goggins', 'motivation', 'The 40% Rule', 'When your mind is telling you that you''re done, that you''re exhausted, that you cannot possibly go any further, you''re only actually 40% done. Your mind gives up long before your body does. The key is to push past that mental barrier, to callus your mind the same way you callus your hands.', '{"book": "Can''t Hurt Me", "chapter": 4}'),
('David Goggins', 'motivation', 'Callousing the Mind', 'The only way to grow is to put yourself in uncomfortable situations. Do the hard things. Run when you don''t want to run. Study when you don''t want to study. The comfort zone is the enemy of growth. Every time you push through discomfort, you build a callus on your mind.', '{"book": "Can''t Hurt Me", "chapter": 5}'),
('David Goggins', 'relapse', 'Taking Souls', 'When you feel like quitting, remember why you started. The accountability mirror doesn''t lie. Look at yourself and ask: are you who you want to be? If not, get after it. No one is coming to save you. You have to save yourself.', '{"book": "Can''t Hurt Me", "chapter": 3}'),
('David Goggins', 'identity', 'The Accountability Mirror', 'Put post-it notes on your mirror with your goals, your insecurities, your lies. Face them every single morning. Be brutally honest with yourself. That''s the only way to change. You can''t fix what you won''t face.', '{"book": "Can''t Hurt Me", "chapter": 2}'),
('David Goggins', 'streaks', 'Stay Hard', 'Every day is a new opportunity to prove to yourself that you are who you say you are. Not through words, but through action. Stack the days. Build the evidence. Your identity changes when your behavior changes consistently.', '{"source": "interviews"}');

-- Marcus Aurelius / Stoicism
INSERT INTO knowledge_base (source, category, title, content, metadata) VALUES
('Marcus Aurelius', 'stoicism', 'Control What You Can', 'You have power over your mind, not outside events. Realize this, and you will find strength. The craving is not in your control. Your response to the craving IS. Focus on what you can control: your next action.', '{"book": "Meditations", "book_number": 6}'),
('Marcus Aurelius', 'stoicism', 'The Present Moment', 'Never let the future disturb you. You will meet it, if you have to, with the same weapons of reason which today arm you against the present. Do not fight tomorrow''s craving today. Win THIS moment.', '{"book": "Meditations", "book_number": 7}'),
('Marcus Aurelius', 'stoicism', 'Impermanence of Pain', 'Pain is neither intolerable nor everlasting if you bear in mind its limits. The craving will pass. It always passes. You just need to outlast it. Usually 15-20 minutes. That''s all. Can you be stronger than 20 minutes?', '{"book": "Meditations", "book_number": 7}'),
('Epictetus', 'stoicism', 'The Dichotomy of Control', 'Some things are within our power, while others are not. Within our power are opinion, motivation, desire, aversion — whatever is of our own doing. Not within our power are our body, property, reputation. The urge is not within your power. Your response is.', '{"book": "Enchiridion", "section": 1}'),
('Seneca', 'stoicism', 'On the Shortness of Life', 'It is not that we have a short time to live, but that we waste a great deal of it. Life is long enough if it is well spent. Every cigarette, every mindless scroll, every drink taken to numb — these are minutes of YOUR life you will never get back.', '{"book": "On the Shortness of Life"}');

-- James Clear / Atomic Habits
INSERT INTO knowledge_base (source, category, title, content, metadata) VALUES
('James Clear', 'habits', 'Identity-Based Habits', 'The most effective way to change your habits is to focus not on what you want to achieve, but on who you wish to become. Every action you take is a vote for the type of person you wish to become. No single instance will transform your beliefs, but as the votes build up, so does the evidence of your new identity.', '{"book": "Atomic Habits", "chapter": 2}'),
('James Clear', 'habits', 'The Four Laws of Behavior Change', 'Make it obvious (cue). Make it attractive (craving). Make it easy (response). Make it satisfying (reward). To break a bad habit, invert: make it invisible, unattractive, difficult, and unsatisfying.', '{"book": "Atomic Habits", "chapter": 3}'),
('James Clear', 'habits', 'The Plateau of Latent Potential', 'Your habits seem to make no difference until you cross a critical threshold. The most powerful outcomes are delayed. You need to be patient. An ice cube doesn''t melt at 30 degrees. At 31 degrees, nothing happens. At 32 degrees, the ice begins to melt. One degree shift unlocked everything.', '{"book": "Atomic Habits", "chapter": 1}'),
('James Clear', 'streaks', 'Never Miss Twice', 'Missing once is an accident. Missing twice is the start of a new habit. The first mistake is never the one that ruins you. It''s the spiral of repeated mistakes that follows. Never miss twice.', '{"book": "Atomic Habits", "chapter": 16}'),
('James Clear', 'triggers', 'Environment Design', 'Environment is the invisible hand that shapes human behavior. If you want to break a bad habit, reduce exposure to the cue that causes it. Make the cues of your good habits obvious and the cues of your bad habits invisible.', '{"book": "Atomic Habits", "chapter": 6}');

-- Addiction Science
INSERT INTO knowledge_base (source, category, title, content, metadata) VALUES
('Addiction Science', 'science', 'Neuroplasticity and Recovery', 'The brain physically changes with addiction — neural pathways strengthen with repeated use. But neuroplasticity works both ways. With each clean day, new pathways form. After 90 days, significant neural rewiring occurs. The cravings literally become weaker because the pathways weaken from disuse.', '{"type": "neuroscience"}'),
('Addiction Science', 'science', 'The Dopamine Cycle', 'Addictive behaviors hijack the dopamine system. The anticipation of the behavior releases more dopamine than the behavior itself. This is why cravings feel so powerful. Understanding this removes their mystery: it''s just chemistry, and chemistry can be changed.', '{"type": "neuroscience"}'),
('Addiction Science', 'science', 'The 90-Day Reset', 'Research shows that after approximately 90 days of abstinence from an addictive behavior, dopamine receptor density begins to normalize. Cravings significantly diminish. Cognitive function improves. This is not willpower — this is your brain literally healing itself.', '{"type": "neuroscience"}'),
('Addiction Science', 'triggers', 'HALT Protocol', 'Most relapses happen when you are Hungry, Angry, Lonely, or Tired (HALT). Before acting on any craving, check: am I HALT? Address the underlying need first. Often the craving disappears when the real need is met.', '{"type": "clinical_psychology"}'),
('Addiction Science', 'relapse', 'Relapse as Learning', 'A relapse is not a failure — it is DATA. It tells you exactly what your vulnerability windows are, what triggers are strongest, and what coping strategies failed. The most successful recoveries involve learning from relapses, not hiding from them.', '{"type": "clinical_psychology"}');

-- Practical Strategies
INSERT INTO knowledge_base (source, category, title, content, metadata) VALUES
('CBT', 'strategies', 'Urge Surfing', 'When a craving hits, don''t fight it or give in. Instead, observe it like a wave. Notice where you feel it in your body. Rate its intensity. Watch it rise, peak, and fall. Cravings typically last 15-20 minutes. If you can surf the urge, it will pass.', '{"type": "cognitive_behavioral_therapy"}'),
('CBT', 'strategies', 'The 10-Minute Rule', 'When tempted, tell yourself: "I''ll wait 10 minutes." Set a timer. During those 10 minutes, do something else — pushups, cold water on face, call someone, walk outside. Often the craving passes. If not, wait another 10.', '{"type": "cognitive_behavioral_therapy"}'),
('ACT', 'strategies', 'Values-Based Action', 'Ask yourself: "What kind of person do I want to be?" Then ask: "Does this behavior align with that person?" If the answer is no, you have your answer. You don''t need motivation — you need alignment with your values.', '{"type": "acceptance_commitment_therapy"}'),
('Practical', 'strategies', 'Implementation Intentions', 'Don''t just decide to quit. Plan the specific situations: "When [TRIGGER] happens, I will [ALTERNATIVE] instead." For example: "When I feel stressed after work, I will do 20 pushups instead of smoking." Specific plans are 2-3x more effective than vague intentions.', '{"type": "behavioral_psychology"}'),
('Practical', 'strategies', 'Social Accountability', 'Tell someone you trust about your goal. Check in with them daily. The knowledge that someone is watching makes you 65% more likely to succeed. Find your accountability partner — not someone who enables, but someone who challenges.', '{"type": "social_psychology"}');
